"""
Design Tokens for DocShipper
hybrid.css theme - CS16 beveled 3D + Classic Mac monochrome
"""

# ============================================
# COLOR PALETTE (hybrid.css)
# ============================================

# Base Monochrome
WHITE = "#FFFFFF"
BLACK = "#000000"
GREY = "#A5A5A5"
LIGHT_GREY = "#C0C0C0"
DARK_GREY = "#404040"
MID_GREY = "#808080"

# Yellow Accent (default buttons)
ACCENT = "#c4b550"
ACCENT_LIGHT = "#d4c870"
ACCENT_DARK = "#958831"

# Blue (OK/execute buttons)
COLOR_OK = "#5080c0"
COLOR_OK_LIGHT = "#70a0e0"
COLOR_OK_DARK = "#3a6090"

# Green (success buttons)
COLOR_SUCCESS = "#5a9a5a"
COLOR_SUCCESS_LIGHT = "#7aba7a"
COLOR_SUCCESS_DARK = "#3a7a3a"

# Red (cancel/danger buttons)
COLOR_DANGER = "#c05050"
COLOR_DANGER_LIGHT = "#e07070"
COLOR_DANGER_DARK = "#903a3a"

# Theme Colors
COLORS = {
    # Primary palette
    "primary": BLACK,
    "accent": ACCENT,
    "accent_light": ACCENT_LIGHT,
    "accent_dark": ACCENT_DARK,

    # Backgrounds
    "background": WHITE,
    "surface": WHITE,
    "secondary_bg": "#E8E8E8",

    # Text
    "text": BLACK,
    "text_muted": DARK_GREY,
    "text_light": WHITE,
    "text_disabled": GREY,

    # Borders (for 3D bevel effect)
    "border": BLACK,
    "border_light": LIGHT_GREY,
    "border_dark": DARK_GREY,

    # Button colors
    "btn_default": ACCENT,
    "btn_default_light": ACCENT_LIGHT,
    "btn_default_dark": ACCENT_DARK,

    "btn_ok": COLOR_OK,
    "btn_ok_light": COLOR_OK_LIGHT,
    "btn_ok_dark": COLOR_OK_DARK,

    "btn_success": COLOR_SUCCESS,
    "btn_success_light": COLOR_SUCCESS_LIGHT,
    "btn_success_dark": COLOR_SUCCESS_DARK,

    "btn_danger": COLOR_DANGER,
    "btn_danger_light": COLOR_DANGER_LIGHT,
    "btn_danger_dark": COLOR_DANGER_DARK,

    # Status colors
    "success_bg": COLOR_SUCCESS,
    "success_border": COLOR_SUCCESS_DARK,
    "warning_bg": ACCENT,
    "warning_border": ACCENT_DARK,
    "error_bg": WHITE,
    "error_border": BLACK,

    # Interactive states
    "hover_bg": "#E8E8E8",
    "selection_bg": ACCENT,
    "selection_text": BLACK,

    # Code
    "code_bg": "#E8E8E8",
}

# ============================================
# TYPOGRAPHY
# ============================================

FONTS = {
    "primary": "'ArialPixel', 'Arial', 'Helvetica Neue', sans-serif",
    "mono": "'Monaco', 'Consolas', 'Courier New', monospace",
}

# Base64 encoded ArialPixel.ttf font
ARIAL_PIXEL_BASE64 = "AAEAAAAOAIAAAwBgRkZUTXhiu0EAACzQAAAAHEdERUYADwAeAAAssAAAAB5PUy8yhbdB9wAAAWgAAABWY21hcC+3oMsAAANMAAABSmN2dCAAIgKIAAAEmAAAAARnYXNw//8AAQAALKgAAAAIZ2x5ZrrejgAAAAVkAAAkqGhlYWQpOR1dAAAA7AAAADZoaGVhBd4CpAAAASQAAAAkaG10eKVLBiIAAAHAAAABjGxvY2HAlcoyAAAEnAAAAMhtYXhwALMAnQAAAUgAAAAgbmFtZbZqndMAACoMAAABqnBvc3RA67n+AAAruAAAAPAAAQAAAAEAAGFuHKhfDzz1AAsEAAAAAADjrO0wAAAAAOOs7TAAAP9AAsACwAAAAAgAAgAAAAAAAAABAAACwP9AAFwDAAAAAAACwAABAAAAAAAAAAAAAAAAAAAAYwABAAAAYwBsAA4AAAAAAAIAAAABAAEAAABAAC4AAAAAAAEBdgH0AAUAAAKZAswAAACPApkCzAAAAesAMwEJAAACAAYDAAAAAAAAAAAAAwAAAAAAAAAAAAAAADJ0dGYAQAAgAKADAP8AAFwCwADAAAAAAQAAAAAAAAF2ACIAAAAAAVUAAAEAAAAAwABAAUAAQAIAAAABwAAAAwAAQAJAAAAAgAAAAUAAAAFAAAABwABAAkAAQADAAAABgABAAMAAQAHAAEABwAAAAcAAQAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAMAAQADAAAACQABAAkAAQAJAAEABgAAAAwAAAAKAAIABwAAAAgAAAAIAAAABwAAAAcAAAAIAAAABwAAAAQAAAAFAAAABwAAAAYAAAAKAAAACAAAAAkAAAAHAAAACgABAAkAAQAIAAAACAAAAAgAAAAIAAAADAAAAAgAAAAIAAAABwAAAAUAAQAGAAAABAAAAAoAAQAIAAAABAABAAcAAAAHAAAABgAAAAcAAAAHAAAABgAAAAcAAAAHAAAAAwABAAQAAAAGAAAAAwABAAsAAQAHAAAABwAAAAcAAAAHAAAABQAAAAYAAAAFAAAABwAAAAYAAAAKAAAABgAAAAYAAAAGAAAABgAAAAIAAAAGAAAACQABAAQAAAAAAAAMAAAADAAAAHAABAAAAAABEAAMAAEAAAAcAAQAoAAAAAYABAABAAIAfgCg//8AAAAgAKD////j/8IAAAEAAAAAAAAAAQYAAAEAAAAAAAAAAAECAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMEBQYHCQAJOQSRKYWTLI8wMTIzNDU2Nzg5Ojs8PT4/QEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl9gYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACICiAAAACoAKgAqACoARABeAKIA5gFSAawBvAHyAiYCUgJyAoYCmAKmAtADBAMmA2YDpAPUBAoERgRyBLgE9AUKBSYFXAV+BbIF5AZUBpIGygcGBzwHageOB9AH+ggYCDgIeAiUCNwJFAlcCYQJ2AoSClgKdgqqCuYLSgugC9YMEAwwDGAMgAyyDMYM2A0MDUANaA2YDdAN+A4wDl4Odg6cDtQO6g8qD1YPhg+6D+oQCBBEEGgQkhC+EQ4RTBGAEbIR4hH6EiwSVBJUAAIAIgAAATICqgADAAcALrEBAC88sgcEAO0ysQYF3DyyAwIA7TIAsQMALzyyBQQA7TKyBwYB/DyyAQIA7TIzESERJzMRIyIBEO7MzAKq/VYiAmYAAAIAQAAAAIACQAAFABMAADM9ATMdASc9BTMdBUBAQEBAQEBAwEBAQEBAQEBAQEBAQAAAAAACAEABwAEAAsAACQATAAATPQMzHQMjPQMzHQPAQMBAAcBAQEBAQEBAQEBAQEBAQEBAAAAABAAAAAABwAJAAAUACwAxADcAADM9ATMdASM9ATMdATc1IxUjNSsBNTsBPQEjNTsBPQEzHQEzPQEzHQEzFSsBHQEzFSMVJz0BIx0BwEDAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQAAAAAIAAP+AAYACgAA1ADsAABc9ASsBNTsBPQIjNSM9ATM1Mz0BMx0BOwIVKwIdAjsBFTMdASM9ASsBHQE7ARUrAR0BAz0BIx0BgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAcBAQEBAAAAOAEAAAALAAkAAAwAJABEAGQAfACUAKwAxADUAPQBFAEsATwBVAAAzNTMVJTMVKwE1Mz0CMx0CKwE9AjMdAQU9ATMdAT0CMx0BJSsBNTsBITMVKwE1ITUzFSM9AjMdAisBPQIzHQEhPQEzHQE9ATMVISsBNTsBwEABQEBAQIBAwEBA/wBAQAEAQEBAQP5AQEBAAQBAwEDAQEABQEBA/sBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAAAAKAAAAAAIAAkAAAwANABkAIQAlAC8AMwA5AD8ASQAAITUzFSUzFSsDNTsBISsBPQEzPQEzHQIFIz0CMx0BJSM1MysDPQEzFTsBMTUzFT0CMx0BISM9ATMVJSsDNTsDAcBA/wBAQEBAQEBAAQBAQEBA/oBAQAEAQEBAQEBAQEBAQED+wEBAAQBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAABAAABwABAAsAACQAAET0DMx0DQAHAQEBAQEBAQEAAAAcAAP9AAQACgAADAAcADQAZAB8AIwAnAAAXNTMVJyM1MysBPQEzFScjPQQzHQMRPQEzHQE9ATMVPQEzFcBAQEBAQEBAQEBAQEBAwEBAQEBAQEBAQEBAQEBAQEBAAQBAQEBAgEBAQEBAAAAAAAcAAP9AAQACgAADAAcADQAZAB8AIwAnAAAVNTMVPQEzFT0CMx0BPQUzHQQDIz0BMxUnIzUzKwE1M0BAQEBAQEBAQEBAQEDAQEBAQEBAQEBAQIBAQEBAQEBAQEBAAUBAQEBAQEAAAAAAAwBAAUABgAKAABcAGwAfAAATPQEjFSM1MzUzPQEzHQEzFTMVIzUjHQE3NTMVISM1M8BAQEBAQEBAQEBAQP8AQEABQEBAQEBAQEBAQEBAQEBAwEBAQAAAAAEAQABAAgACAAAbAAAlPQIrAjU7Aj0CMx0COwIVKwIdAgEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAACAAD/gACAAIAAAwALAAAVNTMVPQMzHQJAQIBAQEBAQEBAQEAAAAAAAQBAAQABQAFAAAkAAAEzFSsDNTsBAQBAQEBAQEBAAUBAQAAAAQBAAAAAgACAAAUAADM9ATMdAUBAQEBAQAAAAAUAQP+AAYACgAAFAA0AEwAbACEAABc9ATMdAT0DMx0CPQIzHQE9AzMdAj0CMx0BQEBAQEBAgEBAQECAQEBAQEBAwEBAQECAQEBAQEBAwEBAQEAAAAQAAAAAAYACQAAJABkAKQAzAAAlMxUrAzU7Aj0GMx0GISM9BjMdBQErAzU7AwEAQEBAQEBAQIBA/sBAQAEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEABgEAAAQBAAAABgAJAAB8AACUzFSsENTsBPQUrATU7ATUzHQcBQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAHAAAAAAGAAkAAAwATABcAHQAhACkAMwAAETUzFQEzFSsFPQEzFTsCJzUzFTczFSsBNTM1MxU9AzMdAicrAzU7A0ABAEBAQEBAQEBAQEBAwEBAQEBAgEBAQEBAQEBAQEBAAcBAQP6AQEBAQEBAQIBAQEBAQEBAQEBAQMBAAAAAAAcAAAAAAYACQAADAA0AFQAZACEAKQAzAAARNTMVEzMVKwM1OwI9AjMdAiEjNTMlKwI1OwIxPQIzHQInKwM1OwNAwEBAQEBAQECAQP7AQEABAEBAQEBAQEBAQEBAQEBAQEABwEBA/oBAQEBAQEBAQECAQEBAQEBAQMBAAAACAAAAAAGAAkAAHQApAAAhPQIrAz0BMzUzNTM1MzUzHQQzFSMdAgMzPQIjFSMVIxUzAQBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAEAQEBAQEBAAAAEAAAAAAGAAkAACQATABcAMwAAJTMVKwM1OwI9AzMdAyEjNTMlKwQ9AzsFFSsEHQE7AwEAQEBAQEBAQIBA/sBAQAEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEDAQEBAQEBAQAAFAAAAAAGAAkAACQATACkALQA1AAAlMxUrAzU7Aj0DMx0DISM9BTMVOwMVKwMdAhE1MxU3MxUrAjUzAQBAQEBAQEBAgED+wEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAFAQECAQEAAAAAFAAAAAAGAAkAAAwAJAA8AFQAlAAAzNTMVPQIzHQE9AjMdAT0CMx0BPQErBDU7BR0BQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQIBAQEBAgEBAQEAABwAAAAABgAJAAAkAEQAZACMAKwAzAD0AACUzFSsDNTsCPQIzHQIhIz0CMx0BJSsDNTsDMT0CMx0CISM9AjMdASUrAzU7AwEAQEBAQEBAQIBA/sBAQAEAQEBAQEBAQEBA/sBAQAEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQECAQAAFAAAAAAGAAkAABwALACEAKwA1AAA3MxUrAjU7ATUzFT0BKwM1OwM9AzMdBSUjPQMzHQIlKwM1OwPAQEBAQECAQEBAQEBAQEBAQP7AQEABAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEDAQAAAAAACAEAAAACAAcAABQALAAAzPQEzHQEDPQEzHQFAQEBAQEBAQAFAQEBAQAAAAAMAAP+AAIABwAADAAkAEQAAFTUzFRE9ATMdAQM9AjMdAkBAQECAQEABwEBAQED+gEBAQEBAQAAABwBAAEACAAIAAAMACQAPABUAGwAhACUAACU1MxUnKwE1OwErAjU7ASsCNTsBNzMVKwE1NzMVKwE1MzUzFQHAQEBAQEBAgEBAQECAQEBAQEBAQEDAQEBAgEBAQEBAQEBAQEBAQEBAQEAAAAAAAgBAAIACAAGAAA8AHwAAJTMVKwY1OwQ3MxUrBjU7BAHAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAwEBAwEBAAAAHAEAAQAIAAgAAAwAJAA8AFQAbACEAJQAANzUzFTczFSsBNTczFSsBNTczFSsBNTErATU7ASsCNTsBKwE1M0BAQEBAQMBAQEDAQEBAQEBAQIBAQEBAgEBAQEBAgEBAQEBAQEBAQEBAAAcAAAAAAUACQAAFAAkADQARABUAGwAjAAAzPQEzHQEnNTMVAzUzFRc1MxU9ATMVPQIzHQEnKwI1OwJAQEBAgEBAQEBAQEBAQEBAQEBAQEDAQEABAEBAwEBAQEBAQEBAQECAQAAJAAD/wALAAkAACwATAC0AOwBFAE8AVwBfAGsAACEzFSsENTsCKwI9ATMVMyUzFSsFNSM9AzM1OwMdBCMzPQMrAh0DMyE9AzMdAyEjPQMzHQIlIzUjNTsBFQU9ATsBFSMVJSsENTsEAcBAQEBAQEBAQEDAQEBAQAGAQEBAQEBAQEBAQEBAQIBAQEBAQAFAQP2AQEACQEBAQED9wEBAQAGAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAwEBAQEBAQEBAgEAAAAYAgAAAAkACQAAFAAsAHwAlACsAMQAAIT0BMx0BIT0BMx0BJSsEPQIzHQE7Aj0BMx0BJyM9ATMVBz0BMx0BPQIzHQECAED+QEABQEBAQEBAQEBAQEBAQEDAQEBAQEBAQEBAQIBAQEBAQEBAQECAQEBAQEBAQECAQEBAQAACAAAAAAGAAkAADQA3AAAlMz0CKwMdAjsBFysDPQg7AxUrAh0COwI9AjMdAzMdAiMVAQBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAABwAAAAABwAJAAAMADQARABUAIQAlAC8AAAE1MxUDMxUrAzU7AjUzFSEjNTMrAT0EMx0DETUzFSUrAzU7AwGAQIBAQEBAQEBAgED+wEBAQEBAQAEAQEBAQEBAQEABwEBA/oBAQEBAQEBAQEBAQEBAQAEAQEBAQAAAAgAAAAABwAJAABcANwAAJTM1Mz0EIzUrAx0GOwEXKwM9CDsEFTMVMx0EIxUjFQEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAQAAAAABgAJAADEAACUzFSsFPQg7BRUrBB0COwQVKwQdAjsCAUBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAABAAAAAAGAAkAAJwAAMT0IOwUVKwQdAjsEFSsEHQNAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAGAAAAAAHAAkAAAwAZAB0AKQAtADcAAAE1MxUDKwM1OwM9ASsBNTsCHQMlIzUzKwE9BDMdAxE1MxUlKwM1OwMBgEBAQEBAQEBAQEBAQEBAQP7AQEBAQEBAAQBAQEBAQEBAQAHAQED+QEBAQEBAQEBAQEBAQEBAQEBAQEABAEBAQEAAAAABAAAAAAGAAkAALQAAIT0DKwMdAyM9CDMdAzsDPQMzHQgBQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAABAAAAAADAAkAAGwAAMysBNTM9BiM1OwIVIx0GMxWAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAACAAAAAAEAAkAABwAdAAA3MxUrAjU7AT0GKwE1OwIdB4BAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAABgAAAAABgAJAAAMAJQApAC0AMQA1AAAhNTMVIT0IMx0DMxUzFTMVMxUjNSM1IzUjHQMTNTMVPQEzFT0BMxU9ATMVAUBA/oBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAUBAQEBAQEBAQEBAQAAAAAABAAAAAAFAAkAAGwAAJTMVKwQ9CDMdBzsBAQBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAIAAAAAAkACQAAnAEkAACE9BiMdASMdASMdASM9ATM9ATM9ATM9ATsBHQghPQg7AR0BMx0BMx0BIz0BIz0BIx0GAgBAQEBAQEBAQED9wEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAEAAAAAAcACQAA7AAAxPQg7AR0BMx0BMxUzHQEzPQYzHQgrAT0BIz0BIzUjPQEjHQZAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAIAAAAAAIAAkAACQANABEAHQApAC0AMQA7AAAlMxUrAzU7AjUzFSEjNTMhPQQzHQQhIz0EMx0DASM1MwU1MxUlKwM1OwMBQEBAQEBAQECAQP7AQEABQED+QEBAAYBAQP6AQAEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAQBAQEBAQEAAAAABAAAAAAGAAkAAKwAAMT0IOwQVMx0CIz0CKwMdAjsDFSsDHQNAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAkAQP+AAkACQAAHABMAFwAbACcAMwA3ADsARQAABTMVKwI1MysBNSsBNTsDFSM3NTMVISM1MyE9BDMdBCEjPQQzHQMBIzUzBTUzFSUrAzU7AwIAQEBAQEBAQEBAQEBAQEBAQP7AQEABQED+QEBAAYBAQP6AQAEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAEAQEBAQEBAAAAAAAIAQAAAAgACQAADADkAACE1MxUhPQg7BBUzHQIjPQIrAx0COwMVIxUzFTMVIzUjNSM1KwEdAwHAQP5AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAABwAAAAABwAJAAAMADwAXABsAJwAvADsAAAE1MxUDMxUrBDU7Az0CMx0CISM1MyUrBDU7BCEjPQIzHQElKwQ1OwQBgECAQEBAQEBAQEBAgED+gEBAAUBAQEBAQEBAQEBA/sBAQAFAQEBAQEBAQEBAQAHAQED+gEBAQEBAQEBAQIBAQEBAQECAQAAAAAABAAAAAAHAAkAAHwAAMz0HKwI1OwYVKwIdB8BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAFAAAAAAHAAkAABwALAA8AHwAvAAAlMxUrAjU7ATUzFSEjNTMhPQYzHQYhIz0GMx0FAQBAQEBAQIBA/wBAQAEAQP6AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAcAAAAAAcACQAAFAAsAEQAXAB0AJQAtAAAzPQEzHQE9AjMdASsBPQEzFTc9ATMdASEjPQEzFSU9AjMdAiEjPQIzHQHAQECAQECAQP8AQEABAED+gEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAsAAAAAAsACQAADAAcAEQAZACEAKwAzADsARQBPAFUAACE1MxUhNTMVJT0DMx0DKwE9AjMdAQU9AjMdAisBPQMzHQIlIz0CMx0BBz0CMx0CJT0DMx0DISM9AzMdAiU9ATMdAQIAQP5AQAGAQIBAQP7AQIBAQAFAQEDAQAFAQP2AQEABAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAADQAAAAABwAJAAAMABwALAA8AFQAbAB8AJQArAC8AMwA3ADsAACE1MxUhNTMVJSM1MwU1MxU3Iz0BMxUHPQEzHQE9ATMVPQIzHQErAT0BMxU3NTMVISM1MyE1MxUhIzUzAYBA/kBAAUBAQP7AQMBAQMBAQECAQECAQP8AQEABAED+gEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAAAAAAAcAAAAAAcACQAALAA8AEwAZAB8AIwAnAAAzPQQzHQQRNTMVKwE1OwE9ATMdASEjPQEzFSU1MxUhIzUzwEBAgEBAgED/AEBAAQBA/oBAQEBAQEBAQEBAQEABQEBAQEBAQEBAQEBAQEBAAAAAAAYAAAAAAYACQAAPABMAGQAdACEAMQAAJTMVKwU9ATMVOwInNTMVPQIzHQE9ATMVPQEzFT0BKwQ1OwUdAQFAQEBAQEBAQEBAQEDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAAAAAAQBA/4ABAAKAACEAABczFSsCPQs7AhUrAR0JwEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAUAAP+AAUACgAAFAA0AEwAbACEAAAU9ATMdAScjPQIzHQEnIz0BMxUnIz0CMx0BJyM9ATMVAQBAQEBAQEBAQEBAQEBAgEBAQECAQEBAQECAQEBAQEBAQEBAgEBAQAAAAAEAAP+AAMACgAAhAAAXKwE1OwE9CSsBNTsCHQuAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAHAEABQAJAAkAAAwAHAAsADwATABcAHQAAATUzFSE1MxUlIzUzBTUzFSUjNTMFNTMVNysBNTsBAgBA/gBAAYBAQP6AQAEAQED/AECAQEBAQAFAQEBAQEBAQEBAQEBAQEBAQAAAAQAA/4ABwP/AAA8AAAUzFSsGNTsEAYBAQEBAQEBAQEBAQEBAQEBAAAIAQAIAAMACgAADAAcAABM1MxUnIzUzgEBAQEACAEBAQEAAAAIAAAAAAYABwAAlAC8AACE1IzUzNSsDHQE7AhUrAjUjPQEzNTsDPQEzHQUDKwM1OwMBQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEABgEAAAAAAAwAAAAABgAKAAB8AKwAzAAAlMxUrBD0JMx0DMxUjHQM7Aj0EMx0EAysCNTsCAQBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEABQEAAAAADAAAAAAFAAcAACQAVAB8AACUzFSsDNTsBKwE9BDMdAxMzFSsDNTsBAQBAQEBAQEBAgEBAwEBAQEBAQEBAQEBAQEBAQEBAQEABQEBAAAAAAAEAAAAAAYACgAAzAAAhNSM1Mz0DKwMdBDsCFSsCNSM9BDM1OwM9AjMdCQFAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAQAAAAAAYABwAAJAA0AJwAxAAAlMxUrAzU7AjUzFSEjPQQzHQE7Az0BMx0CKwQVASsDNTsDAQBAQEBAQEBAgED+wEBAQEBAQEBAQEBAQAEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEABAEAAAAACAAAAAAFAAoAAGQAhAAAzPQUjNTM9ATMdATsBFSsBHQUTMxUrAjUzQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEACgEBAAAAAAAIAAP9AAYABwAAJADsAAAUzFSsDNTsCPQIjNTM9AysDHQQ7AhUrAjUjPQQzNTsEHQgBAEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAADAAAAAAGAAoAADQAlAC0AACE9BTMdBSE9CTMdAzMVIx0EASsCNTsCAUBA/oBAQEABAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAYBAAAIAQAAAAIACQAAPABMAADM9BjMdBgM1MxVAQEBAQEBAQEBAQEBAQEBAQEACAEBAAAMAAP9AAMACQAADAAkAHwAAEzUzFQMzFSsBNTM9ByM1OwEdCIBAgEBAQIBAQEACAEBA/YBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAFAAAAAAFAAoAAAwAjACcAKwAvAAAhNTMVIT0JMx0FMxUzFTMVIzUjNSMdAhM1MxU9ATMVPQEzFQEAQP7AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAEAQEBAQEBAQEAAAAAAAQBAAAAAgAKAABUAADM9CTMdCUBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAFAEAAAAKAAcAADQAdAC8ANQA7AAAhPQUzHQUhPQU7ARUjHQQhPQYzFTMVIx0EASsBNTsBBSsBNTsBAkBA/sBAQED+wEBAQAHAQEBAQP8AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAYBAQEAAAAMAAAAAAYABwAANAB8AJwAAIT0FMx0FIT0GMxUzFSMdBAErAjU7AgFAQP6AQEBAAQBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAGAQAAAAAAEAAAAAAGAAcAACQAVACEAKwAAJTMVKwM1OwI9BDMdBCEjPQQzHQMBKwM1OwMBAEBAQEBAQECAQP7AQEABAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAEAQAADAAD/QAGAAcAAHwArADMAABU9CTMVMxUjHQM7AxUrAx0CAT0EMx0EAysCNTsCQEBAQEBAQEBAQEABAEBAQEBAQEBAwEBAQEBAQEBAQEBAQEBAQEBAQEBAAQBAQEBAQEBAQEBAAUBAAAEAAP9AAYABwAAzAAAFPQMjNTM9AysDHQQ7AhUrAjUjPQQzNTsEHQkBQEBAQEBAQEBAQEBAQEBAQEBAQEDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAIAAAAAAQABwAARABcAADE9BjMVMxUjHQQTMxUrATVAQECAQEBAQEBAQEBAQEBAQEBAQEABwEBAAAAAAAcAAAAAAUABwAADAAsAEQAVAB0AIwArAAABNTMVAzMVKwI1OwE9ATMdASEjNTM3KwI1OwIrAT0BMxU3KwI1OwIBAECAQEBAQECAQP8AQEDAQEBAQEBAwEBAwEBAQEBAQAFAQED/AEBAQEBAQEBAQEBAQEBAAAAAAAIAAAAAAQACQAAFAB0AADczFSsBNTEjPQQjNTM9ATMdATsBFSsBHQPAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAIAAAAAAYABwAAZACcAACE1IxUrAjU7AjUzPQQzHQYlIz0FMx0EAUBAQEBAQEBAQED+wEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAUAAAAAAUABwAAFAA0AFQAbACEAADM9ATMdAT0DMx0CKwE9AjMdATc9ATMdASEjPQEzFYBAQIBAQIBA/wBAQEBAQECAQEBAQEBAQEBAQECAQEBAQEBAQAAJAAAAAAJAAcAABQALABMAGwAjACsAMQA3AD0AACE9ATMdASE9ATMdASU9AjMdAisBPQIzHQEHPQIzHQIrAT0CMx0BJT0BMx0BIT0BMx0BISM9ATMVAYBA/sBAAQBAgEBAwECAQEABgED+wED/AEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEAAAAAACQAAAAABQAHAAAMABwANABMAFwAdACMAJwArAAAhNTMVITUzFTcjPQEzFQc9ATMdAT0BMxU9AjMdASsBPQEzFTc1MxUhIzUzAQBA/sBAwEBAwEBAQIBAQIBA/wBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEAAAAYAAP9AAUABwAAFAA0AFQAdACMAKQAAFz0BMx0BPQMzHQI9AzMdAisBPQIzHQE3PQEzHQEhIz0BMxVAQEBAgEBAgED/AEBAwEBAQECAQEBAQEBAwEBAQEBAQEBAQEBAgEBAQEBAQEAABQAAAAABQAHAAA0AEQAVABkAJwAAJTMVKwQ9ATMVOwEnNTMVPQEzFT0BMxU9ASsDNTsEHQEBAEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAAUAAP+AAUACgAAFAA8AFQAhACcAAAUzFSsBNTEjPQMzHQInKwE1OwExPQQzHQQTMxUrATUBAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEDAQEBAQEBAQEBAQEABgEBAAAEAAP+AAEACgAAZAAAVPQszHQtAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAUAAP+AAUACgAAFAA8AFQAhACcAABczFSsBNTM9AzMdAxMzFSsBNTEjPQQzHQMDKwE1OwFAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAUBAQEBAQEBAQEBAQAEAQAAAAAAFAEAAwAIAAYAABQALABEAFQAbAAA3PQEzHQElMxUrATUzPQEzHQErATUzKwI1OwFAQAEAQEBAgEDAQEBAQEBAQMBAQEBAQEBAQEBAQEBAAAAADgCuAAEAAAAAAAAABwAQAAEAAAAAAAEACgAuAAEAAAAAAAIABgBHAAEAAAAAAAMAEgB0AAEAAAAAAAQACgCdAAEAAAAAAAUAEADKAAEAAAAAAAYACgDxAAMAAQQJAAAADgAAAAMAAQQJAAEAFAAYAAMAAQQJAAIADAA5AAMAAQQJAAMAJABOAAMAAQQJAAQAFACHAAMAAQQJAAUAIACoAAMAAQQJAAYAFADbAHUAbgBuAGEAbQBlAGQAAHVubmFtZWQAAEEAcgBpAGEAbABQAGkAeABlAGwAAEFyaWFsUGl4ZWwAAE0AZQBkAGkAdQBtAABNZWRpdW0AAHUAbgBuAGEAbQBlAGQAOgBBAHIAaQBhAGwAUABpAHgAZQBsAAB1bm5hbWVkOkFyaWFsUGl4ZWwAAEEAcgBpAGEAbABQAGkAeABlAGwAAEFyaWFsUGl4ZWwAAFYAZQByAHMAaQBvAG4AIAAwADAAMQAuADAAMAAwACAAAFZlcnNpb24gMDAxLjAwMCAAAEEAcgBpAGEAbABQAGkAeABlAGwAAEFyaWFsUGl4ZWwAAAAAAgAAAAAAAP+AADMAAAAAAAAAAAAAAAAAAAAAAAAAAABjAAAAAQACAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAvADAAMQAyADMANAA1ADYANwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQAFEAUgBTAFQAVQBWAFcAWABZAFoAWwBcAF0AXgBfAGAAYQECB3VuaTAwQTAAAAAB//8AAAABAAAAAAAAAA4AFgAAAAQAAAACAAAAAQAAAAEAAAAAAAAAAQAAAADMPaLPAAAAAMh4K0EAAAAA46ztMA=="

FONT_SIZES = {
    "xs": "10px",
    "sm": "12px",
    "base": "12px",
    "lg": "14px",
    "xl": "18px",
    "2xl": "24px",
}

FONT_WEIGHTS = {
    "normal": "400",
    "medium": "500",
    "semibold": "600",
    "bold": "700",
}

# ============================================
# SPACING
# ============================================

SPACING = {
    "xs": "4px",
    "sm": "8px",
    "md": "16px",
    "lg": "24px",
    "xl": "32px",
    "2xl": "40px",
}

# ============================================
# BORDERS (3D Beveled Style)
# ============================================

BORDERS = {
    "width": "1px",
    "radius": "0px",  # Sharp corners for retro look
    "radius_lg": "0px",
}

# ============================================
# SHADOWS (Beveled 3D effect)
# ============================================

SHADOWS = {
    # Standard beveled inset (light top-left, dark bottom-right)
    "bevel": f"inset 1px 1px 0 {LIGHT_GREY}, inset -1px -1px 0 {DARK_GREY}",
    # Beveled with drop shadow
    "bevel_raised": f"inset 1px 1px 0 {LIGHT_GREY}, inset -1px -1px 0 {DARK_GREY}, 2px 2px 0 {BLACK}",
    # Pressed/active state (inverted bevel)
    "bevel_pressed": f"inset -1px -1px 0 {LIGHT_GREY}, inset 1px 1px 0 {DARK_GREY}",
    # Input fields (inset)
    "inset": f"inset 1px 1px 0 {DARK_GREY}, inset -1px -1px 0 {LIGHT_GREY}",
}

# ============================================
# TRANSITIONS
# ============================================

TRANSITIONS = {
    "fast": "0.1s ease",
    "normal": "0.15s ease",
    "slow": "0.2s ease",
}

# ============================================
# LETTER SPACING
# ============================================

LETTER_SPACING = {
    "tight": "0px",
    "normal": "0.5px",
    "wide": "1px",
}
